apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  type: NodePort
  selector:
    app: dev-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008   # Keep NodePort same as used before
